### PR TITLE
Parse variables regardless of successful safe check.

### LINKED ISSUE #142: Env variables should be parsed regardless of whether safeCheck is truthy
https://github.com/rubiin/nestjs-easyconfig/blob/f8e9e707dcfb2d27dd7b9e56bebbb8aee099d6b8/src/easyconfig.service.ts#L78

It is my understanding that the `safeCheck` is just to make sure that all the needed env keys are defined, not whether they contain any specific value.

The parsing of variables should happen in all cases, right?

In the current behavior, `safe: false` is required for the env to be parsed using `dotenv-parse-variables`

### PR DESCRIPTION
**Pull request by genu**
Closes #142

### CODE REVIEW

**Comment by genu** [comment]
This PR also fixes an existing issue that causes some tests to fail.

**Comment by genu** [comment]
> we will be prioritizing the config.sampleFilePath and only the fallback will be this.configSample
> so you may have to tweak the sampleFile Variable

This PR keeps that logic intact. It just refactors it so that we can eliminate the extra `return`

The reason that the tests are failing is because we are **returning** `this.safeCheck` if `config.safe` is true.

This PR, (apart from the refactoring I mentioned above) also removes the return of `this.safeCheck`.

What is not clear to me, is what is the relationship between `config.safe` and whether `dotenvParseVariables` should be called or not.

I'm not sure how to update the PR.

**Comment by rubiin** [comment]
@genu fix the merge conflict and i think we are ready to go

**Comment by rubiin** [comment]
> > we will be prioritizing the config.sampleFilePath and only the fallback will be this.configSample
> > so you may have to tweak the sampleFile Variable
> 
> This PR keeps that logic intact. It just refactors it so that we can eliminate the extra `return`
> 
> The reason that the tests are failing is because we are **returning** `this.safeCheck` if `config.safe` is true.
> 
> This PR, (apart from the refactoring I mentioned above) also removes the return of `this.safeCheck`.
> 
> What is not clear to me, is what is the relationship between `config.safe` and whether `dotenvParseVariables` should be called or not.
> 
> I'm not sure how to update the PR.

Actually there is no relation at all. By definition, the configs should be parsed at any condition. Also the return statement was to ensure further processing because if an app misses some keys, it may run into some runtime errors but as we have included the logger message in safe check , that is no longer necessary

**Comment by genu** [comment]
Fixed merge conflicts

**Comment by rubiin** [comment]
Lmgtm

**Comment by rubiin** [comment]
Thanks for your contribution. Keep them coming

**Pull request merged**
